"""Initial migration

Revision ID: 2a87c9b679ad
Revises: 
Create Date: 2024-08-23 22:21:24.267690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a87c9b679ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_events', sa.Column('source_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_log_events_source_type'), 'log_events', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_events_source_type'), table_name='log_events')
    op.drop_column('log_events', 'source_type')
    # ### end Alembic commands ###
